/**
 * Codegen Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Contains auto-generated codegen templates for steps with stepHandler.
 * These templates are used when exporting workflows to standalone projects.
 *
 * Generated templates: 3
 */

/**
 * Auto-generated codegen templates
 * Maps action IDs to their generated export code templates
 */
export const AUTO_GENERATED_TEMPLATES: Record<string, string> = {
  "resend/send-email": `import { Resend } from "resend";
import { fetchCredentials } from "./lib/credential-helper";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

type SendEmailResult =
  | { success: true; id: string }
  | { success: false; error: string };

export type SendEmailCoreInput = {
  emailTo: string;
  emailSubject: string;
  emailBody: string;
};

export async function sendEmailStep(
  input: SendEmailCoreInput,
): Promise<SendEmailResult> {
  "use step";
  const credentials = await fetchCredentials("resend");
  const apiKey = credentials.RESEND_API_KEY;

  if (!apiKey) {
    return {
      success: false,
      error: "RESEND_API_KEY is not configured.",
    };
  }

  const resend = new Resend(apiKey);

  const result = await resend.emails.send({
    from: "onboarding@resend.dev", // Resend's test sender
    to: input.emailTo,
    subject: input.emailSubject,
    text: input.emailBody,
  });

  if (result.error) {
    return { success: false, error: result.error.message };
  }

  return { success: true, id: result.data?.id || "" };
}
`,

  "reverse/Reverse": `import { fetchCredentials } from "./lib/credential-helper";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

type ReverseResult =
  | { success: true; reversed: string }
  | { success: false; error: string };

export async function reverseStep(input: ReverseInput): Promise<ReverseResult> {
  "use step";
  const credentials = await fetchCredentials("reverse");
  if (typeof input.message !== "string" || !input.message.trim()) {
    return { success: false, error: "Message must be a non-empty string" };
  }

  const reversed = Array.from(input.message).reverse().join("");
  console.log(reversed);
  return { success: true, reversed };
}
`,

  "shout/shout": `import { fetchCredentials } from "./lib/credential-helper";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

type ShoutResult =
  | { success: true; shouted: string }
  | { success: false; error: string };

export async function shoutStep(input: ShoutInput): Promise<ShoutResult> {
  "use step";
  const credentials = await fetchCredentials("shout");
  if (typeof input.message !== "string" || !input.message.trim()) {
    return { success: false, error: "Message must be a non-empty string" };
  }

  const shouted = input.message.toUpperCase();
  console.log(shouted);
  return { success: true, shouted };
}
`,
};

/**
 * Get the auto-generated codegen template for an action
 */
export function getAutoGeneratedTemplate(actionId: string): string | undefined {
  return AUTO_GENERATED_TEMPLATES[actionId];
}
