/**
 * Codegen Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Contains auto-generated codegen templates for steps with stepHandler.
 * These templates are used when exporting workflows to standalone projects.
 *
 * Generated templates: 1
 */

/**
 * Auto-generated codegen templates
 * Maps action IDs to their generated export code templates
 */
export const AUTO_GENERATED_TEMPLATES: Record<string, string> = {
  "shout/shout": `import { fetchCredentials } from "./lib/credential-helper";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

type ShoutResult =
  | { success: true; shouted: string }
  | { success: false; error: string };

export async function shoutStep(input: ShoutInput): Promise<ShoutResult> {
  "use step";
  const credentials = await fetchCredentials("shout");
  if (typeof input.message !== "string" || !input.message.trim()) {
    return { success: false, error: "Message must be a non-empty string" };
  }

  const shouted = input.message.toUpperCase();
  console.log(shouted);
  return { success: true, shouted };
}
`,
};

/**
 * Get the auto-generated codegen template for an action
 */
export function getAutoGeneratedTemplate(actionId: string): string | undefined {
  return AUTO_GENERATED_TEMPLATES[actionId];
}
